
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradePlusAdmin.Source.DataBase
{
    using CommonLibrary.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class Client : BaseEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Managers = new HashSet<Manager>();
            this.Purchased_Box = new HashSet<Purchased_Box>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Manager_Id { get; set; }
        public int Client_Status { get; set; }
        public int Client_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Manager> Managers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchased_Box> Purchased_Box { get; set; }
        public virtual ClientStatu ClientStatu { get; set; }
        public virtual ClientType ClientType { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
