//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TradePlusAdmin.Source.DataBase
{
    using CommonLibrary.Models;
    using System;
    using System.Collections.Generic;
    
    public partial class Purchased_Box : BaseEntity
    {
        public int Order_Id { get; set; }
        public int Client_Id { get; set; }
        public int Product_Id { get; set; }
        public Nullable<System.DateTime> Purchase_Time { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Product Product { get; set; }
    }
}
